swagger: '2.0'
host: petstore.swagger.io
basePath: /v2
info:
  title: something
  version: "1.0.0"
paths:
  /v2/projects/{projectId}/landmarks:
    post:
      summary: Add a landmark
      description: ''
      parameters:
        - in: path
          name: projectId
          type: string
          required: true
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Landmark'
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              data:
                $ref: '#/definitions/Landmark'
  /v2/projects/{projectId}/landmarks/${landmarkId}:
    parameters:
        - in: path
          name: projectId
          type: string
          required: true
        - in: path
          name: landmarkId
          type: string
          required: true
    get:
      summary: Get a landmark
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              data:
                $ref: '#/definitions/Landmark'
    delete:
      summary: Delete a landmark
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              data:
                $ref: '#/definitions/Landmark'
    put:
      summary: Update a landmark
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Landmark'
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              data:
                $ref: '#/definitions/Landmark'

definitions:
  Landmark:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      address:
        type: string
      model:
        type: object
      tags:
        type: array
        items:
          type: string
